### ISSUE TITLE
K8s service patch: avoid racing with controller

### ISSUE THREAD

**Issue by sed-i** [canonical/observability-libs#15]
### Bug Description

> We are worried that we're accidentally racing/clobbering the controller patching the object with something important.
> Log messages [like this one](https://github.com/canonical/prometheus-k8s-operator/runs/6823217478?check_suite_focus=true#step:4:1088):
> `ERROR juju.worker.caasapplicationprovisioner.runner exited "prometheus-k8s": Operation cannot be fulfilled on pods "prometheus-k8s-0": the object has been modified; please apply your changes to the latest version and try again`
> It would be ideal to have some hook/event where we know "Juju is done trying to modify these objects, and it's safe to patch it now".
> Is there a time where we can "know" what whatever the controller is trying to do in the message near the top of this is done?
> -- @rbarry82 

### To Reproduce

Deploy charm.

### Environment

Github actions and local.

### Relevant log output

```shell
ERROR juju.worker.caasapplicationprovisioner.runner exited "prometheus-k8s": Operation cannot be fulfilled on pods "prometheus-k8s-0": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by lucabello** [comment]
Closing as we are not using / updating KubernetesServicePatch anymore.
