### ISSUE TITLE
Abstract `ServicePort` from users at instantiation

### ISSUE THREAD

**Issue by DnPlas** [canonical/observability-libs#23]
### Proposal

Change `ports` parameter to receive a list (or iterable) of dictionaries instead of a list of `ServicePort` at instantiation. The library would then have to make `ServicePort` instances for each `port` that is passed.

Example:
```python
# ...
from charms.observability_libs.v1.kubernetes_service_patch import KubernetesServicePatch

class SomeCharm(CharmBase):
  def __init__(self, *args):
    # ...
    tcp = {"port": 443, "name":{f"{self.app.name}-tcp"}, "protocol":"TCP")
...
    self.service_patcher = KubernetesServicePatch(self, [tcp,...])
    # ...
```

### Reasoning

Users need to add `from lightkube.models.core_v1 import ServicePort`. Although not harmful at all, this could create some redundancy in charms that have lightkube abstracted by libraries or packages like [`charmed-kubeflow-chisme`](https://github.com/canonical/charmed-kubeflow-chisme).

**Comment by simskij** [comment]
In that case, I would suggest either creating our own `ServicePort` class in the library, or reexport the lightkube ServicePort class from our lib,  rather than passing "naked" dicts. Would that make sense?

**Comment by lucabello** [comment]
Closing this as not relevant anymore (you should likely use `self.unit.set_ports()` instead), but please feel free to reopen if needed!
