### ISSUE TITLE
[CI] Attempting to run tox without checking if an env exists

### ISSUE THREAD

**Issue by sed-i** [canonical/observability-libs#26]
In CI we run `tox -e <env_name>` without checking first that the env exists:
https://github.com/canonical/observability-libs/blob/3d71ec85541f7f8a01ee059f69c6d9eafc405028/.github/workflows/ci.yaml#L23-L24

This [results in](https://github.com/canonical/cos-configuration-k8s-operator/actions/runs/3150327062/jobs/5122985147#step:5:13):
```
ERROR: unknown environment 'static-lib'
```

(cc: @dstathis re: https://github.com/canonical/cos-configuration-k8s-operator/pull/24)

**Comment by simskij** [comment]
This was fixed as part of the GA release preparations.
