### ISSUE TITLE
cert --> sans

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/observability-libs#55]
### Enhancement Proposal

Originally posted by @sed-i in [this traefik PR](https://github.com/canonical/traefik-k8s-operator/pull/207#discussion_r1276279309)

In the past it used to be the DNS, but now it's deprecated and certs only use SANs.
In the wild (e.g. google) still use something the looks like a hostname in the CN, but it might as well be anything else.
If our method is called cert_subject but in fact produces SANs then we should probably rename it.

**Comment by lucabello** [comment]
Not relevant anymore, as we can pass an optional `cert_subject` to the constructor now, which defaults to `charm.unit.name.replace("/", "-")`.
