### ISSUE TITLE
codeql false positives

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/observability-libs#86]
### Bug Description

Codeql gets triggered by some debug logging in cert_handler, resulting in CI failure and noctua being unable to merge automatic charm lib updates.

See for example in traefik:
https://github.com/canonical/traefik-k8s-operator/pull/342

![image](https://github.com/canonical/observability-libs/assets/6230162/93640744-9b95-4041-ba7f-b071818bc143)

### To Reproduce

https://github.com/canonical/traefik-k8s-operator/pull/342

### Environment

n/a

### Relevant log output

```shell
n/a
```

### Additional context

We should investigate marking this lines as noqa or something like that, or renaming the variables before printing them so codeql won't get touchy about it.

**Comment by ca-scribner** [comment]
Closed as it'll soon be invalid when we move to Tiobe
